data = [
    {"name": "Cristiano Ronaldo", "follower_count": 500, "description": "Professional footballer", "country": "Portugal"},
    {"name": "Taylor Swift", "follower_count": 350, "description": "Singer and songwriter", "country": "United States"},
    {"name": "Lionel Messi", "follower_count": 450, "description": "Professional footballer", "country": "Argentina"},
    {"name": "Ariana Grande", "follower_count": 300, "description": "Singer and actress", "country": "United States"},
    {"name": "Selena Gomez", "follower_count": 290, "description": "Singer and actress", "country": "United States"},
    {"name": "Kylie Jenner", "follower_count": 400, "description": "Entrepreneur and television personality", "country": "United States"},
    {"name": "Dwayne Johnson", "follower_count": 320, "description": "Actor and wrestler", "country": "United States"},
    {"name": "Kim Kardashian", "follower_count": 390, "description": "Television personality and entrepreneur", "country": "United States"},
    {"name": "Beyoncé", "follower_count": 280, "description": "Singer and actress", "country": "United States"},
    {"name": "Justin Bieber", "follower_count": 310, "description": "Singer", "country": "Canada"},
    {"name": "Neymar Jr.", "follower_count": 260, "description": "Professional footballer", "country": "Brazil"},
    {"name": "Katy Perry", "follower_count": 220, "description": "Singer and songwriter", "country": "United States"},
    {"name": "Rihanna", "follower_count": 340, "description": "Singer and entrepreneur", "country": "Barbados"},
    {"name": "Shakira", "follower_count": 200, "description": "Singer and songwriter", "country": "Colombia"},
    {"name": "Elon Musk", "follower_count": 150, "description": "Entrepreneur and CEO", "country": "United States"},
    {"name": "Billie Eilish", "follower_count": 180, "description": "Singer and songwriter", "country": "United States"},
    {"name": "Eminem", "follower_count": 170, "description": "Rapper and music producer", "country": "United States"},
    {"name": "Dua Lipa", "follower_count": 160, "description": "Singer and songwriter", "country": "United Kingdom"},
    {"name": "Post Malone", "follower_count": 190, "description": "Singer and rapper", "country": "United States"},
    {"name": "Adele", "follower_count": 210, "description": "Singer and songwriter", "country": "United Kingdom"},
    {"name": "Kendall Jenner", "follower_count": 230, "description": "Model and television personality", "country": "United States"},
    {"name": "Nicki Minaj", "follower_count": 140, "description": "Rapper and singer", "country": "United States"},
    {"name": "Shawn Mendes", "follower_count": 130, "description": "Singer and songwriter", "country": "Canada"},
    {"name": "Chris Hemsworth", "follower_count": 120, "description": "Actor", "country": "Australia"},
    {"name": "LeBron James", "follower_count": 250, "description": "Basketball player", "country": "United States"},
    {"name": "Emma Watson", "follower_count": 110, "description": "Actress and activist", "country": "United Kingdom"},
    {"name": "Virat Kohli", "follower_count": 100, "description": "Cricket player", "country": "India"},
    {"name": "Gal Gadot", "follower_count": 115, "description": "Actress", "country": "Israel"},
    {"name": "Priyanka Chopra", "follower_count": 105, "description": "Actress and singer", "country": "India"},
    {"name": "Chris Evans", "follower_count": 95, "description": "Actor", "country": "United States"},
    {"name": "Zendaya", "follower_count": 90, "description": "Actress and singer", "country": "United States"},
    {"name": "Bruno Mars", "follower_count": 85, "description": "Singer and songwriter", "country": "United States"},
    {"name": "Jennifer Lopez", "follower_count": 75, "description": "Singer and actress", "country": "United States"},
    {"name": "Chris Pratt", "follower_count": 80, "description": "Actor", "country": "United States"},
    {"name": "Snoop Dogg", "follower_count": 70, "description": "Rapper and entrepreneur", "country": "United States"},
    {"name": "Ellen DeGeneres", "follower_count": 65, "description": "Television host and comedian", "country": "United States"},
    {"name": "Zendaya", "follower_count": 90, "description": "Actress and singer", "country": "United States"},
    {"name": "The Rock", "follower_count": 320, "description": "Actor and wrestler", "country": "United States"},
    {"name": "Cardi B", "follower_count": 60, "description": "Rapper and singer", "country": "United States"},
    {"name": "Kourtney Kardashian", "follower_count": 55, "description": "Television personality", "country": "United States"},
    {"name": "Miley Cyrus", "follower_count": 50, "description": "Singer and actress", "country": "United States"},
    {"name": "Will Smith", "follower_count": 95, "description": "Actor and producer", "country": "United States"},
    {"name": "Ryan Reynolds", "follower_count": 85, "description": "Actor", "country": "Canada"},
    {"name": "Hugh Jackman", "follower_count": 75, "description": "Actor and singer", "country": "Australia"},
    {"name": "Lady Gaga", "follower_count": 300, "description": "Singer and actress", "country": "United States"},
    {"name": "Timothée Chalamet", "follower_count": 65, "description": "Actor", "country": "United States"},
    {"name": "Zendaya", "follower_count": 90, "description": "Actress and singer", "country": "United States"},
    {"name": "Gigi Hadid", "follower_count": 80, "description": "Model", "country": "United States"},
    {"name": "Bella Hadid", "follower_count": 75, "description": "Model", "country": "United States"},
    {"name": "Hailey Bieber", "follower_count": 70, "description": "Model and television personality", "country": "United States"},
    {"name": "Zlatan Ibrahimović", "follower_count": 60, "description": "Professional footballer", "country": "Sweden"},
    {"name": "Roger Federer", "follower_count": 55, "description": "Professional tennis player", "country": "Switzerland"},
    {"name": "Conor McGregor", "follower_count": 50, "description": "Professional fighter", "country": "Ireland"},
]
